services:
  backend:
    build: ./backend
    container_name: Iscte_Games
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://spinu:sZcHr30zj0jNMk54@isctegames.luc3egz.mongodb.net/iscte_games?retryWrites=true&w=majority
      - JWT_SECRET=prefiroQueijadasDeSintra
    depends_on:
      - mongo
    networks:
      - dsa-network      
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo:latest
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=senhaadmin
      - MONGO_INITDB_DATABASE=iscte_games
      - MONGO_INITDB_USERNAME=spinu
      - MONGO_INITDB_PASSWORD=sZcHr30zj0jNMk54
    networks:
      - dsa-network
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  dsa-network:
    driver: bridge

volumes:
  mongodb_data: